ifndef SOURCES
  SOURCES = Visitor.java
endif

ifndef TARGETS
#  TARGETS = Visitor Sum Plus Const Ast RZ
  TARGETS = Sum Plus Const RZ
endif

ifndef SUBDIRSDEF
   SUBDIRSDEF = foo
   SUBDIRS = 
endif

DIR = visitor

include ../Makefile