ifndef SOURCES
  SOURCES = Visitor.java
endif

ifndef TARGETS
  TARGETS = Visitor Sum Plus Const Ast RZ
endif

ifndef SUBDIRSDEF
   SUBDIRSDEF = foo
   SUBDIRS = 
endif

DIR = visitor

include ../Makefile