ifndef TARGETS
  TARGETS = OLIST
endif

ifndef SUBDIRSDEF
   SUBDIRSDEF = foo
   SUBDIRS = 
endif

ifndef CLEAN
  CLEAN = *.proof_file* *.class *~ *.dot \#* .\#* 
endif

DIR = traditional/olist

include ../../Makefile

%.jimple:
	@echo Jimple file provided manually

