ifndef TARGETS
  TARGETS = OLIST
endif

ifndef SUBDIRSDEF
   SUBDIRSDEF = foo
   SUBDIRS = 
endif

ifndef CLEAN
  CLEAN = *.class *~ *.dot \#* .\#* *.proof_file*
endif

DIR = traditional/olist

include ../../Makefile

%.jimple:
	@echo Jimple file provided manually

