ifndef TARGETS
  TARGETS = PERSON STUDENT MUSICIAN SMUSICIAN
endif

ifndef SUBDIRSDEF
   SUBDIRSDEF = foo
   SUBDIRS = 
endif

ifndef CLEAN
  CLEAN = *.proof_file* *.class *~ *.dot \#* .\#* 
endif

DIR = multinh/diamond

include ../../Makefile

%.jimple:
	@echo Jimple file provided manually

