ifndef TARGETS
  TARGETS = CELL BCELL
endif

ifndef CLEAN
  CLEAN = *.class *~ *.dot \#* .\#* *.proof_file*
endif

ifndef SUBDIRSDEF
   SUBDIRSDEF = foo
   SUBDIRS = 
endif

DIR = traditional/cells

include ../../Makefile

%.jimple:
	@echo Jimple file provided manually
