ifndef LIB
	LIB := ../../lib
endif
export LIB

SOURCES = specification.ml cfg_core.ml symexec.ml
INCLUDES = utils prover_syntax symbexe_syntax prover 
RESULT = "$(LIB)/symbexe"
OCAMLLDFLAGS="-a"

include ../Makefile.jstar
