ifndef LIB
	LIB := ../../lib
endif
export LIB

SOURCES = specification.ml symexec.ml
INCLUDES = utils prover_syntax plugin_interface symbexe_syntax prover 
RESULT = "$(LIB)/symbexe"
OCAMLLDFLAGS="-a"

include ../Makefile.jstar
