.TH Alt-Ergo 1 "October, 2006"

.SH NAME
Alt-Ergo \- An automatic theorem prover dedicated to program
verification


.SH SYNOPSIS
.B alt-ergo
[
.B options
]
.B files


.SH DESCRIPTION

.B Alt-Ergo
is an automatic theorem prover.  It takes as inputs an arbitrary
polymorphic and multi-sorted first-order formula written is the Why's
syntax.

.SH OPTIONS

.TP
.B \-h
Help. Will give you the full list of command line options.


.SH AUTHORS
.I Sylvain Conchon <conchon@lri.fr> and Evelyne Contejean <contejea@lri.fr>


.SH SEE ALSO

.I
Alt-Ergo web site: http://alt-ergo.lri.fr
