test: 
	@echo "Running jimple unit tests:" 
	@cd jimple_tests; make test; echo

	@echo "\nRunning prover unit tests:" 
	@cd prover_tests; make test; echo
	
	@echo "\nRunning symbolic execution unit tests:" 
	@cd symb_tests; make test; echo	
