ifndef TARGETS
  TARGETS = PERSON STUDENT MUSICIAN SMUSICIAN
endif

ifndef SUBDIRSDEF
   SUBDIRSDEF = foo
   SUBDIRS = 
endif

ifndef CLEAN
  CLEAN = *.class *~ *.dot \#* .\#* *.proof_file*
endif

DIR = multinh/diamond

include ../../Makefile

%.jimple:
	@echo Jimple file provided manually

