java.util.LinkedList.jimple:
	java soot.Main -f jimple java.lang.Object -d .
	java soot.Main -f jimple java.util.AbstractCollection -d .
	java soot.Main -f jimple java.util.AbstractSequentialList -d .
	java soot.Main -f jimple java.util.LinkedList -d .

