ifndef LIB
	LIB := ../../lib
endif
export LIB

SOURCES = jparsetree.ml jimple_global_types.ml spec_def.ml pprinter.ml

CORESTAR_INCLUDES = utils prover_syntax symbexe_syntax
JSTAR_INCLUDES =
RESULT = "$(LIB)/jimple_syntax"
OCAMLLDFLAGS="-a"

include ../Makefile.jstar