ifndef LIB
	LIB := ../../lib
endif
export LIB

SOURCES = debug.ml dot.ml backtrack.ml misc.ml persistentarray.ml multiset.mli multiset.ml  config.ml system.ml vars.ml load.ml printing.ml
INCDIRS = 
RESULT = $(LIB)/utils
OCAMLLDFLAGS="-a"

include ../Makefile.jstar
