#!/bin/bash

run_vfc -f test_simple.vfc -s test_simple.vspec
run_vfc -f test_loop.vfc -s test_loop.vspec -ai ../../../jabstr/bin/num_abs.cmxs
run_vfc -f test_dma.vfc -s test_dma.vspec 

grep -i contradiction *.txt

grep -i inconsistent *.dot
