ifndef TARGETS
  TARGETS = CEL COUNTER CCELL CCEL2 CLIENT
endif

ifndef SUBDIRSDEF
   SUBDIRSDEF = foo
   SUBDIRS = 
endif

ifndef CLEAN
  CLEAN = *.class *~ *.dot \#* .\#* *.proof_file*
endif

DIR = multinh/ccell

include ../../Makefile

%.jimple:
	@echo Jimple file provided manually

