ifndef TARGETS
  TARGETS = CEL COUNTER CCELL CCEL2 CLIENT
endif

ifndef SUBDIRSDEF
   SUBDIRSDEF = foo
   SUBDIRS = 
endif

ifndef CLEAN
  CLEAN = *.proof_file* *.class *~ *.dot \#* .\#*
endif

DIR = multinh/ccell

include ../../Makefile

%.jimple:
	@echo Jimple file provided manually

