ifndef TARGETS
  TARGETS = OLIST
endif

ifndef CLEAN
  CLEAN =  *.class *~ *.dot \#* .\#* *.proof_file*
endif

ifndef SUBDIRSDEF
   SUBDIRSDEF = foo
   SUBDIRS = 
endif

DIR = traditional/modelbased

include ../../Makefile

%.jimple:
	@echo Jimple file provided manually
