default: 
	cd utils; make
	cd syntax; make
	cd prover; make
	cd proverfront; make
	cd symbexe;  make 

clean: 
	cd utils; make clean
	cd syntax; make clean
	cd prover; make clean
	cd proverfront; make clean
	cd symbexe; make clean