ifndef LIB
	LIB := ../../lib
endif
export LIB

SOURCES = spec.ml core.ml pprinter_core.ml cfg_core.ml 
INCLUDES = utils prover_syntax 
RESULT = "$(LIB)/symbexe_syntax"
OCAMLLDFLAGS="-a"

include ../Makefile.jstar

