ifndef LIB
	LIB := ../../lib
endif
export LIB

SOURCES = spec.ml methdec_core.ml pprinter_core.ml
INCLUDES = utils prover_syntax prover
RESULT = "$(LIB)/symbexe_syntax"
OCAMLLDFLAGS="-a"

include ../Makefile.jstar

